name: BEACONS
favicon: null
layout_spectrum: 0.75077
typography_spectrum: 0.37987
title: Atlanta Deserves Better Districts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070705'
    - '#aa8976'
    - '#753512'
    - '#299194'
  brandStrength: 0.25
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
