name: BEACONS
favicon: null
layout_spectrum: 0.74586
typography_spectrum: 0.37987
title: Atlanta Deserves Better Districts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#22202e'
    - '#bb875f'
    - '#efc885'
    - '#62a0a5'
  brandStrength: 0.6265794327482581
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
