name: Beacons
favicon: null
layout_spectrum: 0.8668635578360409
typography_spectrum: 0.23008826305158436
title: Atlanta Deserves Better Districts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6265794327482581
  lightness: 0.40800941945053637
  saturation: 0.6456971419975162
  rhythmicContrast: 0.8239097825717181
purpose: []
