name: BEACONS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23008826305158436
title: Atlanta Deserves Better Districts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#22202e'
    - '#bb875f'
    - '#efc885'
    - '#62a0a5'
  brandStrength: 0.6265794327482581
  lightness: 0.875
  saturation: 0.6456971419975162
  rhythmicContrast: 0.8239097825717181
purpose: []
